---
  - name: Install postfix
    apt: pkg={{ item }}
    with_items:
      - 'postfix'
    tags:
      - postfix

  - name: Start Postfix on server boot
    service: >
      name=postfix
      state=started
      enabled=yes
    tags:
      - postfix

  - name: Template postfix configuration
    template: >
      src=main.cf.j2
      dest=/etc/postfix/main.cf
    tags:
      - postfix
    notify:
      - restart_postfix
